### ISSUE TITLE
Error when using antigen

### ISSUE THREAD

**Issue by NicholasAntonov** [Tarrasch/zsh-bd#14]
When bundling zsh-bd with `antigen bundle Tarrasch/zsh-bd`, the following error occurs:

```
/home/username/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-bd.git//bd.plugin.zsh:25: condition expected: $1
```

zsh version 5.2

**Comment by Tarrasch** [comment]
Have you debugged this in your own? I don't think I have time to look into this.

**Comment by NicholasAntonov** [comment]
The issue was incorrect line endings caused by my global .gitconfig settings.

Setting ```autocrlf = false``` fixes the problem.
