### ISSUE TITLE
bd into cwd is meaningless

### ISSUE THREAD

**Issue by deluxghost** [Tarrasch/zsh-bd#16]
i dont think bd should accept current dir as an argument, though this sounds not bad, but sometimes confused me. for example, when i am in:

`~/bin/foobar/bin`

and enter:

`bd bin`

i meant go to 

`~/bin`

because that is the first matching parent dir, but bd just let me go to cwd (means nothing happened)

so does the completion, shouldn't show the cwd entry

**Comment by Tarrasch** [comment]
Makes sense to me. Up for creating a patch? :)

**Comment by deluxghost** [comment]
I don't know how to patch that:relieved:
