### ISSUE TITLE
How to install as oh-my-zsh plugin?

### ISSUE THREAD

**Issue by tobiasmuehl** [Tarrasch/zsh-bd#21]
Nice plugin, wondering if it can be installed with oh-my-zsh? Running oh-my-zsh and installed this plugin as explained in the readme without a hitch, but for consistency reasons it would be nice if it played nicely with oh-my-zsh.

**Comment by Tarrasch** [comment]
I've not looked at oh-my-zsh for many years. Does it come with a plugin manager you say? Most zsh plugin managers seem to work by just specifying something the repo identifier `Tarrasch/zsh-bd`. Hope this helps!

**Comment by MrTpat** [comment]
I've made this draft PR that would do what you want: https://github.com/ohmyzsh/ohmyzsh/pull/11415

**Comment by mcornella** [comment]
We already have many plugins. You can use it as a custom plugin instead, see [adding a new plugin](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#adding-a-new-plugin).

**Comment by p1r473** [comment]
@Tarrasch change this repo name to bd instead of zsh-bd
Then we can add it to plugins=(bd)

**Comment by Tarrasch** [comment]
Sorry, I don't have any interest for this plugin to play well with oh-my-zsh. All other zsh plugin managers already play well with this plugin. Like my old https://github.com/Tarrasch/antigen-hs but also https://github.com/zplug/zplug (which I can recommend more than my own plugin).
