### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by CanOfBees** [Tarrasch/zsh-bd#8]
Following the manual install steps, I'm getting the following error when I run `zsh`:
`> zsh 
/usr/home/bridger/.zsh/plugins/bd/bd.zsh: 12: Syntax error: word unexpected (expecting ")")`

I'm not sure what's wrong with the syntax here. Could you advise? I've tried with both 5.0.5 and 5.0.7.
Thanks in advance for your help.

**Comment by CanOfBees** [comment]
Tarrasch, my apologies for leaving this open so long. Your suggestion above worked. 

Thank you for sharing your work.
Cheers!

**Comment by Tarrasch** [comment]
Thanks for reporting the issue! :)
